### ISSUE TITLE
Set up Now + GitHub integration for automatic deployments

### ISSUE THREAD

**Issue by rauchg** [devhubapp/devhub#10]
Ref: https://zeit.co/github

**Comment by brunolemos** [comment]
Added! Thanks.

**Comment by brunolemos** [comment]
Oh it's because I'm using `@now/static` but it required a build before, which I was doing manually. I'll try again with `@now/static-build` soon.

**Comment by brunolemos** [comment]
Done using Travis so it will only deploy on new tag releases.

**Comment by NatanStein** [comment]
olá tudo bom com vocês?
