### ISSUE TITLE
Flexbox grow for pushed commits cards

### ISSUE THREAD

**Issue by LeoColomb** [devhubapp/devhub#107]
The pushed commits cards get lot of space because of the CSS Flexbox grow.
Only visible when more than 2 commits are listed.
If I'm correct, the 2+ commits div height is reflected on the previous div. 

|||
|---|---|
|![image](https://user-images.githubusercontent.com/846943/52266165-fc098a80-2935-11e9-87e0-6cea5ecd692c.png)|![image](https://user-images.githubusercontent.com/846943/52266628-2dcf2100-2937-11e9-9676-b726a0587d86.png)|

On Chrome 73-dev, any platform, but I'm pretty this can be visible anywhere on web.

**Comment by brunolemos** [comment]
Thanks, will check soon. Feel free to make a PR, it should be just one or two lines of code 🙌

RowList.tsx

**Comment by brunolemos** [comment]
I just noticed this wasn't an issue on Chrome 71, just upgraded to 72 and it appeared.
