### ISSUE TITLE
Isn't this an anti-hooks pattern? 

### ISSUE THREAD

**Issue by ahmedlhanafy** [devhubapp/devhub#109]
https://github.com/devhubapp/devhub/blob/fa027892cc59ea033d07275f940be9e5e781795b/packages/components/src/hooks/use-hover.ts#L10

**Comment by brunolemos** [comment]
Hi! 

It's not because `Platform.realOS` will always have the same value since the start.

If it had a dynamic value then it would cause issues with hooks. 

The rule is that the component code must have always the hooks and in the same order on every render, which is the case.

**Comment by brunolemos** [comment]
The only reason to move this to the bottom is to prevent issues when using the Chrome device emulator (if you change between web and a mobile device on chrome you will have to refresh the page otherwise it will get buggy).
