### ISSUE TITLE
Improve notifications layout 

### ISSUE THREAD

**Issue by caioflores** [devhubapp/devhub#11]
I think that it's hard to understand the context of the notifications. In this example, it's not clear that the Tooltip Issue is related to devhub's rep. Icons and fonts have the same size and identation.

<img width="348" alt="screen shot 2018-12-12 at 22 04 41" src="https://user-images.githubusercontent.com/4183877/49908572-fc1b6b80-fe59-11e8-9acb-a39378b69e5a.png">

Maybe some margin-right will do the job.

**Comment by brunolemos** [comment]
Is the activity events design ok? Notifications will have the same soon!

If not, please send some mockups/ideas.

**Comment by caioflores** [comment]
It's okay! But in notifications what will have more focus on the first line, the repository or my user? I think that you can focus on the repository, my profile picture in this context don't add much value.
