### ISSUE TITLE
More messages in case of an empty column

### ISSUE THREAD

**Issue by paulogdm** [devhubapp/devhub#113]
Maybe you should introduce more messages and not only `You rock! :+1:`.
Eg: `Good job! :1st_place_medal:` or `Nice one! :trophy:`
The format is really cool though - good phrase + emoji! After we discuss it I can do a PR.

**Comment by brunolemos** [comment]
Yes we can add more messages and emojis!
Do you have some suggestions?

Here's the code: https://github.com/devhubapp/devhub/blob/e2af02af468e5ffe0ab62e9785cf2a531cb0f09d/packages/components/src/components/cards/EmptyCards.tsx#L17-L25

**Comment by brunolemos** [comment]
One thing I'm considering for fun it adding a confetti cannon when you clear the column, something like [this](https://codepen.io/jscottsmith/pen/VjPaLO) from the bottom left and bottom right:

<img alt="confetti cannon gif" height="400" src="https://user-images.githubusercontent.com/619186/52665250-48366b00-2ef2-11e9-9b1d-286c1367fa4d.gif" />

**Comment by paulogdm** [comment]
Oh, so you already implemented what I had in mind! Nice!
Indeed the animation would be cool.
Thank you @brunolemos !
