### ISSUE TITLE
Mark a single notification or activity as done

### ISSUE THREAD

**Issue by caioflores** [devhubapp/devhub#12]
It would be great a check button in each activity/notification so we can mark as read without having to open the link.

**Comment by brunolemos** [comment]
That's planned for the notifications! For the events I'm not sure, I think just the current clear button + save button is easier to manage.

**Comment by ArondeParon** [comment]
This seems to be "Done" but I have a hard time finding this feature. I can mark things as "read" but they still show up in the columns. Is there a way to clear everything that I have seen?

**Comment by brunolemos** [comment]
@ArondeParon not yet, I do plan to add that but I'll need to think of a new UI because there is no space for more buttons anymore.

**Comment by brunolemos** [comment]
This issue was closed because previously the "Check" button at the top only cleared read items, but now it clears all items.

**Comment by HumairAK** [comment]
Hello, looking through the app I still cannot find a way to mark a single item "done", I see that I can "clear" a column, but I don't think that's the same as marking it "done" as I can do so via the github notificaitons UI. As mentioned earlier, I can mark items as "read" but marking them "done" removes them from the inbox in the ui, is there a way to accomplish something similar via this app?

**Comment by timharris777** [comment]
@brunolemos, can this be re-opened? I just downloaded devhub to give it a try and the first thing I noticed is no easy way to mark a single notification as done. Also, marking a notification as done in devhub should mark it as done in the github notifications interface.
