### ISSUE TITLE
Android app is not being updated

### ISSUE THREAD

**Issue by brunolemos** [devhubapp/devhub#128]
Lot's of users complained they still have an old version (e.g v0.45)~, and the Play Store doesn't show an Update button for the latest version~. It's like they already updated, but the app is still the old one.

The weird part is that the "App Details" inside Android settings does show the latest version.

Does anyone have any idea?

![image](https://user-images.githubusercontent.com/619186/54450733-ee62d400-472f-11e9-974b-4510be8d4d81.png)

![image](https://user-images.githubusercontent.com/619186/54450891-3eda3180-4730-11e9-8389-a183fe2cb6c2.png)

**Comment by LeoColomb** [comment]
> Play Store doesn't show an Update button

It does, but the updated app does not seem to come from a fresh build.
Are you sure this is not an issue with a compilation cache?

**Comment by brunolemos** [comment]
I use the new App Bundle mode instead of apk, maybe it has some bug with react native? Not sure. Need to investigate.

**Comment by bmeverett** [comment]
Might be an issue with bundling. I know I've pushed an update to the store but forgot to bundle the latest code 🤦‍♂️

**Comment by zhigang1992** [comment]
@brunolemos our app also uses App Bundle, but updates fine.

Our issue was forget to TypeScript compile to js. 

But DevHub is different since it reference the `.ts` and `.tsx` directly, should not need to compile to js first.

**Comment by brunolemos** [comment]
All the `.aab` I uploaded since December wasn't updated correctly :(
So everyone still had a very old version :(

It seems it generated correctly now, please update and let me know if it shows v0.48+ at the bottom of the preferences screen! https://play.google.com/store/apps/details?id=com.devhubapp
