### ISSUE TITLE
Topbar: ui layout issue

### ISSUE THREAD

**Issue by hushicai** [devhubapp/devhub#13]
The topbar layout seems to be a bit problematic.

![image](https://user-images.githubusercontent.com/1249423/49917862-d767d800-fedb-11e8-90bd-aa3f0fbc40a2.png)

iPhone7, IOS 10.13.3

**Comment by brunolemos** [comment]
@hushicai thanks for trying it out!

I was able to reproduce this on an old ios version.
Please upgrade your iOS to v12+ if you can.

![image](https://user-images.githubusercontent.com/619186/49918604-ec684b00-fe8a-11e8-876f-b9edb5e79bb7.png)

**Comment by brunolemos** [comment]
This will be fixed in the next react-native version (0.58): https://github.com/facebook/react-native/pull/18534 (https://github.com/facebook/react-native/commit/3949e937cc0c032965cbffa0c7b6c0f702f12e01)

**Comment by brunolemos** [comment]
This will be fixed in the next react-native version (0.58): https://github.com/facebook/react-native/pull/18534 ([commit](https://github.com/facebook/react-native/commit/3949e937cc0c032965cbffa0c7b6c0f702f12e01))

**Comment by brunolemos** [comment]
_Deployed on v0.40.0_
