### ISSUE TITLE
Internalization problem

### ISSUE THREAD

**Issue by RooQI** [devhubapp/devhub#136]
Hello Bruno.
Your project is amazing. I am full of admiration. I want to think of using monorepo in my future project. However, I need support for multiple languages. Devhub does not support this and I decided to try adding it myself using the `react-native-localize` package. However, I received the error `Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH)`. I added the plugin to the `packages/web/package.json` and wrote it in `packages/web/config-overrides.js`, but this did not help. Webpack still does not see the plugin. Do you have any thoughts on how to add a plugin or work around this error? 
Thanks.

**Comment by brunolemos** [comment]
Thanks!

Are you sure this package supports web? In the readme I see there is a native "link" step so it probably won't work on web. Try looking for a js-only localiation package or confirm if this one has web support.

Also prefer adding dependencies in packages/components instead of packages/web.

**Comment by brunolemos** [comment]
I'd love to have devhub available on multiple languages, so if you find a good setup for web+mobile please let me know or send a pull request!

**Comment by RooQI** [comment]
Hello Bruno. 

Thanks for your help. I'll let you know if I find a solution.
