### ISSUE TITLE
Permit enhanced filtering of issue notifications for a repository

### ISSUE THREAD

**Issue by kadamwhite** [devhubapp/devhub#14]
Feature request:

When I'm looking at the available options for a repository, it's not obvious how to (or if it's possible to) limit notifications in the column to only those issues where I have subscribed, been mentioned, have participated, or have had my review requested. On a high-traffic repository like wordpress/gutenberg the noise can quickly drown out the signal without this sort of limiting filter, so I'd like to request that DevHub be enhanced with the ability to focus on issues where we have explicitly participated.

Thanks much!

**Comment by brunolemos** [comment]
@kadamwhite just to be clear, you have checked these filters and they weren't enough, right? Or they solve the issue?

![image](https://user-images.githubusercontent.com/619186/50038910-e94a9780-000f-11e9-8171-e86b7d6c3ba0.png)

**Comment by brunolemos** [comment]
Lot's of filters have been added since this issue was open, including `inbox:participating` and `reason` filters:

![image](https://user-images.githubusercontent.com/619186/67632481-7d1cff00-f882-11e9-911d-bcafb98b055e.png)
