### ISSUE TITLE
Make window draggable

### ISSUE THREAD

**Issue by A-Hilaly** [devhubapp/devhub#143]
Currently the twitter deck have a top section making it draggable (moving the application to different positions in the screen)

![Screenshot 2019-05-30 at 14 49 28](https://user-images.githubusercontent.com/10897901/58633932-397d9380-82ea-11e9-95b0-a3e4a32efe07.png)

I don't know if that is possible but It can be nice to have the same section or feature for devhub !

**Comment by brunolemos** [comment]
Hi! On macOS you can drag windows by click+holding the window borders and moving them:

![Kapture 2019-05-30 at 12 15 18](https://user-images.githubusercontent.com/619186/58642998-cb7aa180-82d4-11e9-9885-49018a298a06.gif)

Currently Linux/Windows have a title bar.

_Duplicated of #111_
