### ISSUE TITLE
Change long press behaviour for tabs

### ISSUE THREAD

**Issue by msfjarvis** [devhubapp/devhub#147]
The long press action seems to create a [dialog](https://user-images.githubusercontent.com/13348378/59316740-952e2080-8cdd-11e9-884b-a13183e8c08b.png) that simply shows the name of the tab. I personally find it to be a waste of precious contextual space, and instead would like to suggest repurposing it as a delete action, with a confirmation dialog or an undo UI flow, whatever feels more natural to you.

**Comment by brunolemos** [comment]
Thanks for the suggestion! Long pressing it will probably be used to reorder the columns. 

Pull Requests for drag&drop are more than welcome! #80 was started but it was not cross-platform so it was not merged.

**Comment by MSF-Jarvis** [comment]
I'm a native Android developer, React and Typescript are still not part of my skill set so I'll just wait for someone capable of executing this to drop by :)

**Comment by brunolemos** [comment]
Closing in favor of #42. Also on `v0.94.3`. this alert will be removed.
