### ISSUE TITLE
Invalid repo name when having a `.`

### ISSUE THREAD

**Issue by Atinux** [devhubapp/devhub#148]
It seems that the repo name cannot have a `.` in its name:

![Screenshot 2019-06-12 at 13 03 45](https://user-images.githubusercontent.com/904724/59346607-f91f0c00-8d12-11e9-8712-c90bb8f961a1.png)

Apparently it comes from this line where the repo name regex is taken from username regex: https://github.com/devhubapp/devhub/blob/c544c53481ef2836e45a81f7e8190ca5417e42a0/packages/core/src/helpers/github/shared.ts#L60

PS: Keep up the great work on DevHub <3

**Comment by brunolemos** [comment]
Thanks for reporting! Will release a fix in the next patch version.

**Comment by brunolemos** [comment]
_v0.91.1 available with the fix cc @Atinux_

**Comment by Atinux** [comment]
That was fast! Thank you @brunolemos
