### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by Jack-Chronicle** [devhubapp/devhub#150]
I'm not actually sure what's wrong, I got the .AppImage, loaded it up (and clicked yes to integrate) and immediately got an error... clicked OK, the app loaded, and then the error showed up again. Attached the two errors that showed up for me as well, in case anyone can figure out how to fix them, or make sense of it... The second error will continue to show up rapidly after I click the OK button, so it doesn't go away. Luckily I can still close out of devhub to prevent it from continuing
Will update if I get anything new, or figure out how to fix it. Until then, any help is greatly appreciated
![devhub_error_01](https://user-images.githubusercontent.com/18507378/60069250-52058180-96cf-11e9-8242-244b7ea7a120.png)
![devhub_error_02](https://user-images.githubusercontent.com/18507378/60069251-52058180-96cf-11e9-85b7-9be97cd80ea1.png)

If you need to know, i'm running Solus OS, and the latest version of devhub. It should be running fine as far as I know...

**Comment by brunolemos** [comment]
Thanks for reporting!

Based on the error message, it's probably these lines:

https://github.com/devhubapp/devhub/blob/1b7fa33a439322a887c1b2261c759709cb15db68/packages/desktop/src/menu.ts#L411-L43

They are missing a `label`.

I'll deploy a new version later today or tomorrow with a fix.

**Comment by brunolemos** [comment]
Could you send a pr? Should not be hard. My linux virtual machine stopped working, I have to setup again.

**Comment by moluoyu** [comment]
ubuntu18.04 has the same quession.
