### ISSUE TITLE
[Challenge] Improve performance

### ISSUE THREAD

**Issue by brunolemos** [devhubapp/devhub#155]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24200%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/devhubapp/devhub/issues/155)

### About the problem

This app, DevHub, renders too many items at once: It can have dozens of columns, and each column can render hundreds of items.

This affects memory usage, scrolling and animations performance. Doing simple tasks like scrolling or opening modals starts to be laggy on this situation (see gifs below).

**Can you make it blazing fast™?**

_Important note: This is a react-native-web project. This challenge is for the web part only._

![gif](https://user-images.githubusercontent.com/619186/60048043-9bd77300-96a1-11e9-96c3-ad4ebd33e550.jpg)

![gif](https://user-images.githubusercontent.com/619186/57186724-f979eb00-6eba-11e9-8f36-a992ae402567.gif)

![Kapture 2019-06-26 at 17 45 29](https://user-images.githubusercontent.com/619186/60213832-ad07b780-983a-11e9-8e11-2b09456da280.gif)

### The solution

**Virtualized lists** exists to solve this problem. With them, the app would render only the visible items (~5 columns, ~5 items per column), which would be around 25 items instead of hundreds.

Virtualization is a must-have for this kind of project.

#### Attempt #1: FlatList

[FlatList](https://github.com/necolas/react-native-web/issues/1337) has a built-in virtualization. It actually works super great on native mobile, but at the web this happens:

_(same gif as shown above)_

![gif](https://user-images.githubusercontent.com/619186/57186724-f979eb00-6eba-11e9-8f36-a992ae402567.gif)

So I decided to disable virtualization: https://github.com/devhubapp/devhub/search?q=disableVirtualization&unscoped_q=disableVirtualization

This is the result without virtualization:

![gif](https://user-images.githubusercontent.com/619186/57186733-23cba880-6ebb-11e9-8e26-893caede2f22.gif)

Looks great, right? But it's not a sustainable solution, only works well for <100 items. Disabling virtualization has other consequences as well, like animations, memory usage, first-render time, etc. So we shouldn't disable virtualization, we kinda need it.

#### Attempt #2: react-window

I thought the performance issue was with `FlatList`, so I decided to try [react-window](https://github.com/bvaughn/react-window). You can check the code on this branch: https://github.com/devhubapp/devhub/pull/152

Same problem happened: the app actually felt slower instead of faster when enabling virtualization. 

I'm not sure why, but I suspect the components rendering are too expensive _(ps: may not be it! needs more investigation; I couldn’t find the root cause of the performance issues yet, maybe you can?)_.

There's definitely lot's of script running while scrolling (see [this comment](https://github.com/devhubapp/devhub/issues/155#issuecomment-508962515) for an updated screenshot): 

![image](https://user-images.githubusercontent.com/619186/60212440-a3c91b80-9837-11e9-8b78-d1c52fb20de3.png)

### Challenge

Can you fix the performance? Can you find what’s the root cause is? Is the only solution re-writing the components to make them less expensive? Would React Concurrent mode help? Is it because the react tree is rendering too many components? Is it because of the position of the planets? 🤪

Do you have any other guesses or insights? Let us know in the comments!
Please try your guesses locally in your machine to see the results.

### How to run the web project

It's super quick to get it up and running:

- `git clone git@github.com:devhubapp/devhub.git`
- `cd devhub`
- Enable virtualization for web
  - Option 1 _(using react-window)_: `git checkout react-window` (https://github.com/devhubapp/devhub/pull/152)
  - ~Option 2 _(using FlatList)_: Search the app code and replace all `disableVirtualization` props to `false` and all `removeClippedSubviews` props to `true`~
- `yarn`
- Run
  - Debug mode: `yarn dev:web`
  - Release mode: `yarn workspace @devhub/web build && yarn workspace @devhub/web serve`

After running the [web] project, make it slow: Create lot's of columns, and tap "Load more" on each one to have lot's of items loaded. See how some animations and scrolling starts to become laggy.

## Prize

To win the bounty, you need to submit your code changes in a pull request with a considerable performance fix.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $200.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($200.00)
### Submitted pull Requests
- [#173 Performance boost + Redesign](https://issuehunt.io/r/devhubapp/devhub/pull/173)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/devhubapp/devhub/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by gaearon** [comment]
>yarn dev:web

Are you sure you're not running into fixed overhead of DEV mode?

**Comment by brunolemos** [comment]
@gaearon hi dan, yes I tried on both debug and release.

**Comment by alizahid** [comment]
I’m building an app with a very similar layout and running into the same problems. Will share findings/solutions!

**Comment by OriginLive** [comment]
https://blog.discordapp.com/using-rust-to-scale-elixir-for-11-million-concurrent-users-c6f19fc029d3
https://blog.discordapp.com/why-discord-is-sticking-with-react-native-ccc34be0d427
Read these two. Their engineering blog shows answers on some of those questions you guys have. Hope it helps

**Comment by brunolemos** [comment]
OriginLive, thanks for the links! But this issue is related to the web; react-native performance is actually ok. They said in the article they made their list in objective-c, which doesn’t apply here for web. Need some specific investigation.

**Comment by brunolemos** [comment]
Here’s a screenshot of the Chrome’s performance tab (click to zoom):

<img width="1440" alt="Screen Shot 2019-07-06 at 20 17 33" src="https://user-images.githubusercontent.com/619186/60762387-1f477b80-a035-11e9-8468-b439c6936764.png">

When the new item is added to the dom, you can see the FPS dropped to `6` (other frames have 72fps).  

To get the result above, I used `react-window`’s `FixedSizeList` and scrolled super slowly. It’s using dev version of react so I can see the component names.

So I believe the main cause of the performance issue is that my components are expensive to render, but still needs more investigation (why are they expensive?).

**Comment by brunolemos** [comment]
Okay I've just re-watched Dan's [Beyond React 16](https://youtu.be/nLF0n9SACd4) and Andrew's [Concurrent React](https://youtu.be/ByBPyMBTzM0) awesome talks and I'm convinced Time Slicing could help us here. 

In fact @gaearon even [mentioned](https://youtu.be/nLF0n9SACd4?t=10m04s) in the video that it improves scrolling responsiveness, which may be the main thing we need here based on my findings above.

Needs to make react-native[-web] support Concurrent Mode first though (Caleb sent me his fork: https://github.com/calebmer/react-native-web).

I'll try it next, I'm excited!

**Comment by brunolemos** [comment]
I used `react-window`, enabled `Concurrent Mode`, optimized `react-native-web` styles and unfortunately the result still isn’t satisfactory: https://alpha.devhubapp.com  ([code](https://github.com/devhubapp/devhub/pull/152))

_Note: also it’s quite buggy since react-window’s `DynamicSizeList` is not production ready yet_

**Comment by brunolemos** [comment]
I have found that some components are calling some ""expensive"" methods on render, like the functions [stripMarkdown](https://github.com/devhubapp/devhub/search?utf8=✓&q=stripMarkdown&type=) and [getReadableColor](https://github.com/devhubapp/devhub/search?utf8=✓&q=getReadableColor&type=). When removing these methods I can notice an improvement. 

Need to search for more work that I can remove from render.

**Comment by polarathene** [comment]
If certain methods are quite expensive but their results don't take up too much memory, you could look at using memoization? Moize is a good library for this where you can limit the cache size with various settings(LRU limit, expiry time, etc). You could perhaps also warm that cache layer up with your list data prior to rendering the first time via virtualized list if you're getting a notable hit with first appearance of a list item.

Rendering wise, a virtual list helps, but you can also take into account how the browser groups/layers content for paint/rasterization. Prior to that, ensure that React isn't needlessly re-rendering components because of changes such as a new item coming into view on the virtual list.

I came across this from the issuehunt site btw, I'm quite busy but if I end up with some free time, I might give this a shot as this is my kind of thing :)

**Comment by brunolemos** [comment]
@polarathene thanks for taking the time!

I'm currently rewriting parts of the app, mainly the card components, to be simpler and less expensive. Result is looking promising so far, I'll know for sure in a couple days!

**Comment by RichardLindhout** [comment]
React-native-web components are slower than normal components. It also helps to rewrite list items in a web version with normal css.
