### ISSUE TITLE
when run dev:desktop show 'Using the "className" prop on <View> is deprecated.'

### ISSUE THREAD

**Issue by Usern2me** [devhubapp/devhub#157]
when i open a new window on dev mode,console log 'Using the "className" prop on <View> is deprecated.' for many times.

**Comment by brunolemos** [comment]
Hi! This has been fixed a while ago with this commit: https://github.com/devhubapp/devhub/commit/8a244de8753259485c2530271dbbc85169e8bd79

Are you sure you have the latest commits locally? Try the following:

- `git fetch --all`
- `git pull`
- `yarn --force`

**Comment by Usern2me** [comment]
> Hi! This has been fixed a while ago with this commit: [8a244de](https://github.com/devhubapp/devhub/commit/8a244de8753259485c2530271dbbc85169e8bd79)
> 
> Are you sure you have the latest commits locally?
> 
> I see your fork is outdated. Try forking again or run the following:
> 
> * `git remote add upstream git@github.com:devhubapp/devhub.git`
> * `git fetch --all`
> * `git pull upstream master`
> * `git push`
> * `yarn --force`

thank u ~
