### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by brunolemos** [devhubapp/devhub#161]
It’s been 7 months since DevHub is available but it doesn’t have a Landing Page yet. 

The GitHub repository has served this purpose, but only for people being linked to github. For people coming directly to devhubapp.com (e.g. from other websites , like Google search) all they see is a Login page.

The Landing Page should:

- List the main app features
- Have a modern design (maybe something like [intercom](https://www.intercom.com), [hyperping](https://hyperping.io), [baremetrics](https://baremetrics.com))
- Be optimized for SEO

We can use Next.js, Gatisby or maybe plain old HTML+CSS without JavaScript. Next.js preferred.

**Comment by johnletey** [comment]
@brunolemos I'd be more than happy to work on this!

**Comment by brunolemos** [comment]
Thanks @johnletey!

I am working on it (#162) to practice Next.js and Tailwind CSS.
Feel free to play with the branch `landing` but I’ll probably do it in the next few days.

**Comment by johnletey** [comment]
Sounds good @brunolemos! I'll take a look at the `landing` branch and see what I can help out with!
