### ISSUE TITLE
Performance Web on Firefox Quantum 68.0.2 (64-bit)

### ISSUE THREAD

**Issue by Shekcon** [devhubapp/devhub#172]
First access devhub web more than 5s or even 15s to loading web. Everything works so slowly.
When i switch tab from devhub to other tabs then whole web is reloading again.
![image](https://user-images.githubusercontent.com/39558457/63446745-f3594b80-c464-11e9-930b-27bf43d066aa.png)
So I test devhub web on Google Chrome. It runs well and smonthly.

**Comment by brunolemos** [comment]
Hi, yes, thanks for reporting. 
It’s related to a react-spring bug: https://github.com/react-spring/react-spring/issues/767

I’ve fixed this locally and will release a new version pretty version soon. 

I’m rewriting a part of the app to have better performance and design, it will be great!

**Comment by brunolemos** [comment]
Please try the beta and let me know if it's better: https://beta.devhubapp.com/

_PS: This beta is still a work in progress and is missing some existing features from the non-beta version._

**Comment by phenrique7** [comment]
Same issue here in Firefox Developer Edition. Now, I just tried the beta and, wow, the performance is much better and I liked the new design too. Waiting excited for the new version.

**Comment by Shekcon** [comment]
> Please try the beta and let me know if it's better: https://beta.devhubapp.com/
> 
> _PS: This beta is still a work in progress and is missing some existing features from the non-beta version.

It works well and smonthly.

**Comment by martinbroos** [comment]
@brunolemos could you explain how you fixed the performance issues with react spring in firefox?
