### ISSUE TITLE
Preset default filters 

### ISSUE THREAD

**Issue by ayox** [devhubapp/devhub#174]
Hi there , Great application. I wanted to just give a feedback about filters. I like that we have filters, however, I think if we could get filters preset from devhub itself and with the option to remove them and maybe with an indication of how to. I have added two projects and I feel like it's cluttered and overwhalming with things I wouldn't normally care. For example, I am normally not concern with who stared the repo I follow.

Nevertheless , I have been enjoying using it so far thanks.

**Comment by brunolemos** [comment]
Hi! Not sure I understood. Do you mean that new columns should have some fillers by default?

**Comment by ayox** [comment]
New and existing columns; by default all filters options are ticked which means that I would need to go and untick the ones I don't want. I think there should be some default filters from devhub to help reduce the noise in the column. 
I think this could be labeled as feature request.
