### ISSUE TITLE
Adding the titlebar to the mac app

### ISSUE THREAD

**Issue by linuxjuggler** [devhubapp/devhub#176]
I was wondering if there is any plan to add a title bar to the mac application.

Small functionality like minimizing, maximizing and even closing the window is nice to have, especially that moving the window around needs some **search** within the issues to figure out that clicking on the thin borders is what you need to be able to move the window around.

But, if you clicked on the border and moved it up, you will end up resizing the window, so you will need to choose the direction carefully.
The title bar can have just the main buttons + the moving functionality no need to have the title of the application.. etc.

Like this

![Screen Shot 2019-09-03 at 9 30 00 AM](https://user-images.githubusercontent.com/27624/64148988-6ed7d700-ce2d-11e9-896a-767140bac23d.png)

Thanks

**Comment by vjpr** [comment]
Yes please! It's impossible to minimize it.

**Comment by brunolemos** [comment]
> It's impossible to minimize it.

@vjpr you can use `Window > Minimize` or the Cmd+M for now

**Comment by vjpr** [comment]
@brunolemos I can't seem to drag it either. Cmd+M is not working. Cmd+W is working.

**Comment by linuxjuggler** [comment]
@vjpr dragging is tricky, as mentioned you should click on a border and move the mouse to the left or right

**Comment by brunolemos** [comment]
Added on [v0.97.0](https://github.com/devhubapp/devhub/releases/tag/v0.97.0).

**Comment by linuxjuggler** [comment]
Great, thanks 👍

**Comment by linuxjuggler** [comment]
@brunolemos may I suggest adding a slim border-bottom to the title-bar to make it a bit obvious and more delightful?
