### ISSUE TITLE
Can't find variable: Intl

### ISSUE THREAD

**Issue by peanutDD** [devhubapp/devhub#188]
formatPrice@index.android.bundle:500:1534
PricingPlanBlock@index.android.bundle:1237:2050
Or@index.android.bundle:91:41719
Vl@index.android.bundle:91:80200
Ml@index.android.bundle:91:70036
Ul@index.android.bundle:91:67144
Ul@[native code]
Pl@index.android.bundle:91:65839
Pl@[native code]
index.android.bundle:91:25495
unstable_runWithPriority@index.android.bundle:170:3915
sn@index.android.bundle:91:25442
cn@index.android.bundle:91:25377
_e@index.android.bundle:91:88686
Ne@index.android.bundle:91:13582
Ue@index.android.bundle:91:13755
receiveTouches@index.android.bundle:91:14547
value@index.android.bundle:38:3685
index.android.bundle:38:841
value@index.android.bundle:38:2939
value@index.android.bundle:38:813
value@[native code]

**Comment by brunolemos** [comment]
Thanks for reporting, I shipped this code by mistake. 
Published the fix to the store and it should be available in a few hours.

_Note: It will still say `0.97.1`_
