### ISSUE TITLE
Android client

### ISSUE THREAD

**Issue by Suburbanno** [devhubapp/devhub#19]
I searched but did not find

**Comment by brunolemos** [comment]
Not live yet! Should be soon.

**Comment by brunolemos** [comment]
The app has some android specific issues, seems to be mostly caused by an old version of JavaScript. Upgrading the JSC should fix it: https://github.com/react-community/jsc-android-buildscripts

I'll do it in a couple days, but pull requests are welcome.

**Comment by brunolemos** [comment]
Making progress on #50. Good news is that the JSC upgrade fixed all the crashes and critical bugs, now just a few tweaks left.

**Comment by brunolemos** [comment]
Android app is now available: [Link](https://play.google.com/store/apps/details?id=com.devhubapp)
I consider this an alpha, so please open issues here with the bugs you find or improvement suggestions!

cc @SaraVieira
