### ISSUE TITLE
menubar on windows not working

### ISSUE THREAD

**Issue by tobiaskohlbau** [devhubapp/devhub#190]
I tried to switch into menubar mode and the app is displayed once on the top left of the screen. If I click once anywhere else on the screen the menubar version of devhub closes and after that I'm unable to open it again. Every click on the icon within the taskbar opens the settings/context menu. Even selecting the 'open' option from within the context menu does not appear to have any effect.

If you need more information, let me know.

**Comment by brunolemos** [comment]
Let me know if [v0.98.0](https://github.com/devhubapp/devhub/releases/tag/v0.98.0) fixes it!

**Comment by tobiaskohlbau** [comment]
Works like a charme, thanks for the fix!

**Comment by brunolemos** [comment]
@tobiaskohlbau thanks for purchasing the yearly plan! 💚

**Comment by tobiaskohlbau** [comment]
@brunolemos I'm thankful for your work. You've solved every point I've told you via email in roughly one week. If that is not worth a one year subscription I don't know what is.
