### ISSUE TITLE
[Windows] Menubar mode wrong behavior

### ISSUE THREAD

**Issue by ju2pom** [devhubapp/devhub#191]
It would be really nice if we could minimize DevHub to the system tray and see a feedback in the icon when a new notification arrive.

**Comment by brunolemos** [comment]
Have you tried the "Menubar" mode?

**Comment by ju2pom** [comment]
Hi,
Good point I didn't try !
Now that I've tried I'm not sure it's working as expected.
Here is gif file showing how it behaves on my computer.
![r8JP7L9E2y](https://user-images.githubusercontent.com/3799294/66778458-0835e680-eecc-11e9-90eb-f8cf57e818cf.gif)

**Comment by brunolemos** [comment]
Weird, I just tried on Windows 10 and I'm not able to reproduce these problems. Tried with the sidebar at the right like yours and it worked correctly. Not sure what could be.

**Comment by ju2pom** [comment]
Good guess, after clicking again on `Menubar mode` the "popup" is displayed and then when I left click on the icon the popup opens correctly. If I right click on the icon and then click "open" it works too.
Just to let you know I could reproduce the same issue I reported on my personal and professional computers. I have two screens configuration for both with vertical taskbar.

**Comment by brunolemos** [comment]
@ju2pom what about the window position? is it still showing up at the top left (wrong) or at the bottom right (correct)?

**Comment by ju2pom** [comment]
The windows position seems to be correct, it's next to the systray icon.

**Comment by tobiaskohlbau** [comment]
That described behavior is the same as I experienced in #190.

**Comment by brunolemos** [comment]
Let me know if [v0.98.0](https://github.com/devhubapp/devhub/releases/tag/v0.98.0) fixes it.
