### ISSUE TITLE
Remove #partial-timeline from new issue URLs

### ISSUE THREAD

**Issue by pantharshit00** [devhubapp/devhub#192]
Right now whenever I click on an item which is a new issue, devhub appends `#partial-timeline` (which I believe is coming from the API) at the end of the URL.

My biggest problem which this is Github's Slack integration refuses to show the preview for these URLs and it is annoying to strip this part out each time.

Example:
![image](https://user-images.githubusercontent.com/22195362/66944098-25a0b700-f06a-11e9-90f1-2a534c72c919.png)

**Comment by brunolemos** [comment]
Most of the time the person clicks on a link on DevHub they want to read the latest comment, which is at the bottom. The `#partial-timeline` makes it scroll to the bottom. So I don't think we should remove this from DevHub. Maybe you could send a bug report to Slack?

**Comment by pantharshit00** [comment]
Opened: https://github.com/integrations/slack/issues/956

**Comment by brunolemos** [comment]
Thanks!
