### ISSUE TITLE
Unable to locate attached view in the native tree

### ISSUE THREAD

**Issue by astrelsky** [devhubapp/devhub#193]
exports@index.android.bundle:25:287
value@index.android.bundle:242:2469
value@index.android.bundle:242:1530
value@index.android.bundle:255:2217
value@index.android.bundle:255:2297
Ln@index.android.bundle:91:32405
di@index.android.bundle:91:50450
Ml@index.android.bundle:91:70036
Ul@index.android.bundle:91:67144
Ul@[native code]
Pl@index.android.bundle:91:65839
Pl@[native code]
index.android.bundle:91:25495
unstable_runWithPriority@index.android.bundle:170:3915
sn@index.android.bundle:91:25442
cn@index.android.bundle:91:25377
_e@index.android.bundle:91:88686
Ne@index.android.bundle:91:13582
notify@index.android.bundle:624:871
notifyNestedSubs@index.android.bundle:624:443
handleChangeWrapper@index.android.bundle:624:518
[native code]
j@index.android.bundle:633:5905
index.android.bundle:1276:312
index.android.bundle:1268:9884
index.android.bundle:1275:371
index.android.bundle:1268:2798
h@index.android.bundle:1268:288
T@index.android.bundle:1268:477
E@index.android.bundle:1268:337
index.android.bundle:1268:2754
index.android.bundle:1268:7318
T@index.android.bundle:1268:8303
A@index.android.bundle:1268:7819
v@index.android.bundle:1268:8080
f@index.android.bundle:108:155
index.android.bundle:108:882
y@index.android.bundle:114:661
C@index.android.bundle:114:1025
callImmediates@index.android.bundle:114:3100
callImmediates@[native code]
value@index.android.bundle:38:3247
index.android.bundle:38:1283
value@index.android.bundle:38:2939
value@index.android.bundle:38:1253
value@[native code]
value@[native code]

I'm not exactly sure what happened here. This was auto loaded though.  Hopefully the information helps. I just had a software update for my phone this morning so it may be related.

**Comment by brunolemos** [comment]
Thanks for reporting, I checked bugsnag and it seems this only affected 2 users. It seems to be an edge case and you'll likely not face this again.

If it keeps happening let me know that I'll investigate more.
