### ISSUE TITLE
Can't download mac app.

### ISSUE THREAD

**Issue by watanabeyu** [devhubapp/devhub#195]
Hi there.
I want to download devhub app on mac, but can't download by below link.

https://github.com/devhubapp/devhub/releases/tag/v0.97.1
https://github.com/devhubapp/devhub/releases/download/v0.97.1/DevHub-0.97.1-mac.zip

please fix this link.

**Comment by brunolemos** [comment]
@watanabeyu What happens when you try to download? I just tried and it worked as expected. Maybe some problem on your internet that is blocking it?

**Comment by watanabeyu** [comment]
@brunolemos thanks to reply.
I tried to download, but displayed below.

https://gyazo.com/4284e2e414e41a8e10016f0ae6b85d2a

but I tried now,  can download.

sorry to bother you.
