### ISSUE TITLE
[Windows] save button on app tries to open a native link

### ISSUE THREAD

**Issue by tobiaskohlbau** [devhubapp/devhub#198]
The newly added save button on the windows app tries to open an app (system-url) which windows does not know the filetype and shows the selection to download one from the store. The shortcut executed with `s` does not have this behavior so I assume it's a native link which needs to get removed?

Edit:
I forgot to notice, that the opening is executed in addition to saving the notification.

**Comment by brunolemos** [comment]
Thanks for reporting, it seems this was happening only on Windows.

I have re-uploaded the [.exe](https://github.com/devhubapp/devhub/releases/download/v0.98.0/DevHub.Setup.0.98.0.exe) file on [v0.98.0](https://github.com/devhubapp/devhub/releases/tag/v0.98.0) with the fix. You can re-install it to get the fix now or wait for the `v0.98.1`+ release which may take a few days.

**Comment by tobiaskohlbau** [comment]
Can confirm that this works. Looks like you've misspelled the file, beforehand it was called `DevHub-Setup-0.98.0.exe` now it's called `DevHub.Setup.0.98.0.exe` that why your reference on [devhubapp.com](https://devhubapp.com/download) does not work.

**Comment by brunolemos** [comment]
Fixed, thanks! It seems that when I re-uploded manually GitHub replaced the spaces with “.”, and when electron-builder uploads automatically it replaces the spaces with a “-“.
