### ISSUE TITLE
Scrollbars on firefox

### ISSUE THREAD

**Issue by pantharshit00** [devhubapp/devhub#200]
Right now you will get pretty bad looking scroll bars on firefox. On chrome they are hidden so they are not blocking the content. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22195362/70927891-dd941580-2055-11ea-8b67-a82e563bb2af.png">

I noticed that you hide the scrollbars using some webkit properties:
<img width="242" alt="image" src="https://user-images.githubusercontent.com/22195362/70927989-087e6980-2056-11ea-9b85-1355108965ac.png">

These are not supported on firefox as expected so you will need to use properties without prefix to hide those:
https://stackoverflow.com/questions/20997183/how-to-hide-scrollbar-in-firefox

**Comment by brunolemos** [comment]
Thanks, fixed! I disabled all scrollbars except the horizontal one at the bottom.

Any reason why you are not using the desktop app instead?

**Comment by pantharshit00** [comment]
I am trying to minimize electron app usuage if they have a browser alternative.
