### ISSUE TITLE
⌘= should trigger zoom in

### ISSUE THREAD

**Issue by diegohaz** [devhubapp/devhub#201]
Currently, it's possible to zoom in by pressing <kbd><kbd>⌘</kbd><kbd>+</kbd></kbd>. But we have to press <kbd>Shift</kbd> in order to produce the <kbd>+</kbd> character. It took me some time to figure that out. Most apps allow us to use <kbd><kbd>⌘</kbd><kbd>=</kbd></kbd> instead.

**Comment by brunolemos** [comment]
_Implemented on [v0.100.0](https://github.com/devhubapp/devhub/releases/tag/v0.100.0)_
