### ISSUE TITLE
Filter by owner/repo doesn't work with mutiple values

### ISSUE THREAD

**Issue by wardpeet** [devhubapp/devhub#203]
It seems like I can't filter with multiple users/orgs. Unsure if this is a feature request or a bug.

![image](https://user-images.githubusercontent.com/1120926/71245551-46f57c00-2315-11ea-899b-91afb6aef8e4.png)

**Comment by brunolemos** [comment]
You can do it after you create the column, just not while creating the column.

**Comment by wardpeet** [comment]
Could you explain how? Whenever I use the search and switch between icons it disappears.

**Comment by brunolemos** [comment]
After creating a `owner:wardpeet` filter you can click the search button and add `owner:someorg`.

But you are right, it’s disappearing.

For now, as a workaround, try clicking holding the Alt key to negate the filter (or click on the “tag” filter to negate it as well, the ones at the left of the search button).

**Comment by brunolemos** [comment]
@wardpeet After creating a `owner:wardpeet` filter you can click the search button and add `owner:someorg`.

But you are right, it’s disappearing.

For now, as a workaround, try clicking on their “tags” to negate them:

![Kapture 2019-12-20 at 17 32 15](https://user-images.githubusercontent.com/619186/71287189-6527a000-2346-11ea-9cdb-7644dbe1c81b.gif)

**Comment by brunolemos** [comment]
>  Whenever I use the search and switch between icons it disappears.

@wardpeet I think I understood better what you meant now. You need to press enter after typing at the search filter to submit it.

**Comment by brunolemos** [comment]
I improved this on [v0.100.0](https://github.com/devhubapp/devhub/releases/tag/v0.100.0).

It better handles multiple owners now:

![gif](https://user-images.githubusercontent.com/619186/72762837-d8c80180-3bbf-11ea-83d5-f9a0fb655c54.gif)

I also extended your free trial.
Thanks.
