### ISSUE TITLE
Subscription reason: Review requested user only (not team)

### ISSUE THREAD

**Issue by diegohaz** [devhubapp/devhub#204]
I'd like to filter a column by review requests to users only (not teams). For example, I'd like to show PRs that requested review from @diegohaz, with the option to exclude teams of which I'm member.

The problem is that I'm part of a team on https://github.com/Automattic whose review is **always** requested because it's the owner of the codebase. The repository has plenty of new PRs every day. It's impossible to keep track, so I ended up turning off the notifications on GitHub. But that also means that I won't be notified when someone requests my review (not my team).

**Comment by brunolemos** [comment]
I added this on [v0.100.0](https://github.com/devhubapp/devhub/releases/tag/v0.100.0).

Let me know if that works as expected.

I also extended your free trial.
Thanks.
