### ISSUE TITLE
less invasive fullscreen mode

### ISSUE THREAD

**Issue by maxandersen** [devhubapp/devhub#206]
I have a 49" ultrawide monitor I really don't want any app to forcefully take up the full screen  - no matter how awesome they are.

Could there be a way to not have devhub go in full screen but just show the window when clicking the icon in the dock ?

**Comment by maxandersen** [comment]
if anyone else interested I've for now used hammerspoon to force devhub windows to stay at a specific size. it still goes full screen but I at least don't have to manually resize it every time :)

**Comment by brunolemos** [comment]
I'm not sure I understood the problem you are facing.

> Could there be a way to not have devhub go in full screen but just show the window when clicking the icon in the dock ?

"Full screen" forces full screen but it doesn't seem that's the option you want.

There is the "Desktop mode" option, where you can resize the window the way you want and it will only show the app when clicking at the dock. Isn't that what you are looking for?

You can toggle between maximized/non-maximized by clicking twice at the window title bar.

<img width="1440" alt="Screen Shot 2020-01-22 at 14 54 13" src="https://user-images.githubusercontent.com/619186/72919926-109d8900-3d27-11ea-9e9d-f828c0a66309.png">

**Comment by maxandersen** [comment]
I'm not sure how i ended up in the staate but I was using Desktop mode and had resized the window but everytime when I click on the devhub icon it went back to full screen or rather fully maxmized.

Now I've clicked on toggle full screen and it seem like it stopped doing that. 

Could it be that somehow devhub remembers one have click "maximized" and then on button click keeps going maxmized ? 

anyway, the behavior stopped now after clicking on more of those items in devhub menu - but the first two days it keep just maxmizing when i clicked devhub.

**Comment by brunolemos** [comment]
This may be fixed on v0.102.0 since I fixed a very similar issue that was affecting Linux and Windows!
