### ISSUE TITLE
How to transition page in opposite direction when hit back button?

### ISSUE THREAD

**Issue by ksoldau** [devhubapp/devhub#210]
`"react-spring": "^8.0.27",`

I have an app with multiple pages, let's call them A, B, and C. When a user goes from A -> B, or B -> C I want the pages to "slide right". When a user goes "back" from C -> B or B -> A I want the pages to "slide right". No matter the transition, if any of the pages are rendered to the screen they should show in this order from right to left: A, B, C.

The animations from A -> B -> C work fine. Example: when the user goes from A to B, A and B are briefly on the screen together in that order, and both slide to the left. However, I cannot figure out how to "reverse" the animation when clicking the back button. What I want is for A and B to be on the screen in that order, and for both to slide to the right. Instead, what I currently have is the order of components on screen as B then A, and the transition is sliding to the right. 

Here's a simplified example of what I'm talking about: https://codesandbox.io/s/happy-forest-f2w03

Any help would be appreciated! I haven't been able to find examples of this situation anywhere, even though I think it's a fairly common use case.

**Comment by brunolemos** [comment]
Hi, 

I don't provide support for react-spring, but you need to update your `from` and `leave` transitions to act different when it's going back.

Here's it working: https://codesandbox.io/s/modest-bush-2ex9i

```diff
import { render } from 'react-dom'
import React, { useState, useCallback, useRef } from 'react'
import { useTransition, animated } from 'react-spring'

import './styles.css'

const pages = [
  ({ style }) => <animated.div style={{ ...style, background: 'lightpink' }}>A</animated.div>,
  ({ style }) => <animated.div style={{ ...style, background: 'lightblue' }}>B</animated.div>,
  ({ style }) => <animated.div style={{ ...style, background: 'lightgreen' }}>C</animated.div>,
]

export default function App() {
  const [index, set] = useState(0)

+  const lastPressedBackRef = useRef(false)

  const onClick = useCallback(() => {
+    lastPressedBackRef.current = false
    set(state => (state + 1) % pages.length)
  }, [])

  const transitions = useTransition(index, p => p, {
+    from: () => lastPressedBackRef.current ? { transform: 'translateX(-100%)' } : { transform: 'translateX(100%)' },
    enter: { transform: 'translateX(0%)' },
+    leave: () => lastPressedBackRef.current ? { transform: 'translateX(100)' } : { transform: 'translateX(-100)' },
  })

  const goBack = useCallback(() => {
+    lastPressedBackRef.current = true
    set(state => (state + pages.length - 1) % pages.length)
  }, [])

  return (
    <>
      <button onClick={goBack}>Go back</button>
      <div className="simple-trans-main" onClick={onClick}>
        {transitions.map(({ item, props, key }) => {
          const Page = pages[item]
          return <Page key={key} style={props} />
        })}
      </div>
    </>
  )
}

render(<App />, document.getElementById('root'))
```

**Comment by ksoldau** [comment]
So sorry @brunolemos! Added the issue to the wrong tab. 
Thanks so much for the support, though.
