### ISSUE TITLE
App no MacOS não funciona

### ISSUE THREAD

**Issue by renanmav** [devhubapp/devhub#222]
Estou apenas com uma tela preta.

![Captura de Tela 2020-10-16 às 16 12 11](https://user-images.githubusercontent.com/43140758/96299416-6bb88f80-0fca-11eb-8a36-8b8637abf8fc.png)

**Comment by brunolemos** [comment]
primeira vez que vejo isso; mac ta com espaco livre suficiente? ja tentou reinstalar o app?

**Comment by brunolemos** [comment]
@renanmav v0.102 funciona?

**Comment by renanmav** [comment]
@brunolemos Estou usando no Windows agr
