### ISSUE TITLE
Feature Request: Organize stars in groups

### ISSUE THREAD

**Issue by ksketo** [devhubapp/devhub#24]
This goes beyond the existing functionality provided by github but one of the features I have really wanted for a while now is to be able to organize my stars in groups, something similar to https://astralapp.com/ .

Cool project btw!

**Comment by jacobrosenthal** [comment]
Same for orgs. users. etc. I dont necessarily want 10 mostly empty columns, but want to group all those together under some tag and follow that as a whole in one column

**Comment by brunolemos** [comment]
@jacobrosenthal please open a separate issue for that!

**Comment by brunolemos** [comment]
I gave this some thought.

DevHub is used to keep up to date with activities, and this is more like a organization tool for already-starred repositories. So I believe it's a bit out of scope. 

This is better as a separate project.

Thanks for the suggestion!

> Note: There is a small chance we eventually add a "Stars" column, but it would only allow to filter by languages (like [github.com](https://github.com/ksketo?tab=stars) already do), and not to add custom tags like [astralapp.com](https://astralapp.com/)
