### ISSUE TITLE
Web: remove reset.css

### ISSUE THREAD

**Issue by necolas** [devhubapp/devhub#3]
Global reset (or CSS files) should not be used in this context. If there's a reason why you have the reset, please let me know. Same goes for the styles in index.css.

**Comment by brunolemos** [comment]
@necolas true, it's not needed! Removed.

The other css I'll keep for now, they are very small, e.g.:

```
.snap-container {
  scroll-snap-type: x mandatory;
}

.snap-item-start {
  scroll-snap-align: start;
}
```

The `pagingEnabled` was not having any effect on the web, but it does on mobile. Another CSS I'm using is css variables to change the theme with better performance.

**Comment by necolas** [comment]
I understand the need for the paging functionality while that is not available. I think you could/should remove all this though:

```
* {
  transition: all 0.2s ease-out;
  box-sizing: border-box;
}

.touchable-opacity {
  transition: all 0.2s ease-out, opacity 0s;
}

*:focus {
  outline: none;
}

* {
  box-sizing: border-box;
}

html, body, #root, #root > div {
  width: 100%;
  height: 100%;
  overflow: hidden;
}

body {
  background-color: #1c1c1c;
}
```

You can move the styles bound to `html, body, #root, #root > div` into the HTML shell file as inline styles in the elements. And move the rest of the CSS into a style tag there to avoid CSS work in the build step
