### ISSUE TITLE
unnecessary / wrong link to play store 

### ISSUE THREAD

**Issue by StackOverflowIsBetterThanAnyAI** [devhubapp/devhub#307]
Hey, I am not familiar with this repository, so I cannot really tell from the outside if this intended. 

It seems that the app is not available in the Google Play Store. This means that the Button linking to the Google Play Store inside your README.md is no longer necessary or should link to a different source if you published the android app somewhere else.

Kind regards

Michael

**Comment by StackOverflowIsBetterThanAnyAI** [comment]
the same applies to the 'Download links:' -> 'Android' section in the README.md file

**Comment by WarFiN123** [comment]
You can find the apk in the releases section
