### ISSUE TITLE
DevHub GitHub login api broken

### ISSUE THREAD

**Issue by Chaprnks** [devhubapp/devhub#309]
![noEx8lX](https://github.com/devhubapp/devhub/assets/6340970/58d536d3-cbf8-43b0-9c6d-58259947d9e0)

![VcxkoG5](https://github.com/devhubapp/devhub/assets/6340970/3a437685-daa0-4559-9d7a-a77dba3f3a49)

**Comment by aakashbasa** [comment]
I am getting the same issue as well when I try to authenticate `DevHub` with my `GitHub`


<img width="872" alt="Screenshot 2024-05-28 at 11 06 43 PM" src="https://github.com/devhubapp/devhub/assets/39308879/e1aa8df1-3b9f-40fe-abfc-6a4ad52a0a6d">

**Comment by maxlibin** [comment]
same problem

**Comment by mauriciord** [comment]
@brunolemos any updates?
