### ISSUE TITLE
New column should be located at the end by default

### ISSUE THREAD

**Issue by luongvo** [devhubapp/devhub#35]
Like Trello columns, new column should be located at the end, we're focusing about the main things first

**Comment by brunolemos** [comment]
It was like this at the beginning, but because of the way I implemented the `Add Column` modal (at the left of the screen), the UX was a bit weird with the column being added at the end. So not sure about it.

**Comment by luongvo** [comment]
Yeah, as my suggestion, let move user activity, dashboard and notifications to the start by default is better. Add more column should be on the bottom of the list on the left :)
![image](https://user-images.githubusercontent.com/16315358/50040241-5e4eb900-0072-11e9-9bdf-e22e593c47c5.png)

**Comment by felicianotech** [comment]
I agree with this. Not only is it like Trello as the OP said, it's like Tweetdeck which is what this is modeled after.

**Comment by brunolemos** [comment]
_Deployed on v0.39.2_
