### ISSUE TITLE
Improve iOS bottom bar design

### ISSUE THREAD

**Issue by avelino** [devhubapp/devhub#39]
The icons are small to the dictionary some columns, ends up disturbing the usability (it's my point of view)

The icons are small to the dictionary some columns, ends up disturbing the usability (it's my point of view)

![46b0fe19-ed09-4674-914e-6ad6c626a7b9](https://user-images.githubusercontent.com/31996/50053152-f0100200-0116-11e9-8f6d-1af229a7342b.jpeg)

**Comment by brunolemos** [comment]
How do you think it should be?

**Comment by avelino** [comment]
apple pattern
![r1vai](https://user-images.githubusercontent.com/31996/50072987-42582e00-01be-11e9-9a41-5a6c1c7d649d.png)

ref: https://developer.apple.com/design/human-interface-guidelines/ios/bars/tab-bars/
