### ISSUE TITLE
Theme change is not intuitive

### ISSUE THREAD

**Issue by FabioRosado** [devhubapp/devhub#41]
Hello,

I've decided to check your project and looks great so thanks for creating it 😄 👍 

When I try to choose one of the three dark themes, they don't work. Any button that I press on the light theme changes the ui straight away but not the dark ones.

On my first try of DevHub I tried to change the theme to Dark Blue and nothing changed, then later on the ui changed to the dark blue theme out of nowhere - I tried to refresh the page but it doesn't seem to have any effect.

Are the dark themes only activated after a certain time (like night time)? Or is this a bug?

I'm using Safari 12.0.1

**Comment by LucasNaja** [comment]
Hi dear,
Maybe you've auto toggle button on, try turning them off

this feature changes the theme according to the time of day, please hung up

**Comment by brunolemos** [comment]
Hi! You need to disable the "auto toggle" button to be able to change themes like @LucasNaja said, otherwise it will only change on day/night switch. 

A couple people didn't find this intuitive so I may tweak this a little.

**Comment by brunolemos** [comment]
Made a couple changes on how theme change works, should be more intuitive now.

_Deployed on v0.39.2_
