### ISSUE TITLE
This is not an Open Source project

### ISSUE THREAD

**Issue by avinassh** [devhubapp/devhub#53]
The readme says: 

>  And more!: Native apps, keyboard shortcuts, open source, modern tech stack, ...

However this is not a open source project since it does have not a compatible license: https://github.com/devhubapp/devhub/blob/53f8023d4b6bf3babdc1a101204a7b23b11b0549/LICENSE.md

https://opensource.org/licenses

**Comment by brunolemos** [comment]
For me, what matters is that everyone can read the code, learn from it, fork and contribute.

But okay, I removed the `open source` text from the README for now.

I'm open to changing the license, please send your specific license suggestions on #33.
