### ISSUE TITLE
Android feedback

### ISSUE THREAD

**Issue by Suburbanno** [devhubapp/devhub#55]
I've been facing some lags and lockups in the transitions, and where's the bottom bar?

[Video here](https://drive.google.com/file/d/14kHLK0MTeAnauo_ada00KakrKaEIDTeF/view?usp=drivesdk)

**Comment by Suburbanno** [comment]
![](https://i.imgur.com/ef633R7.png)

**Comment by brunolemos** [comment]
Thanks for reporting! What's the device model and android version?

**Comment by Suburbanno** [comment]
Motorola Moto E5 plus, Android 8.0

**Comment by brunolemos** [comment]
@Suburbanno released v0.40, please let me know how is it!

https://play.google.com/store/apps/details?id=com.devhubapp

If you have huge lags I'd love any help on that, I don't have an android device, only emulator.

**Comment by Suburbanno** [comment]
@brunolemos thanks for the update, had an improvement but I still have lags in the transitions, it's time to change the theme too, and to with a problem with the text where the user is, is cutting, not aligned, good job!!

[Video here](https://drive.google.com/file/d/1qfBNz6XU6i3lSQrkbFL7si5X1UF6TwRX/view?usp=drivesdk)

**Comment by brunolemos** [comment]
Theme change is currently slow on all mobile devices, opened #68 for this.

About the other issues, I'll check but please consider making some pull requests as well. I don't have an android device and most issues doesn't happen on the emulator.

**Comment by kiliman** [comment]
Hi @brunolemos 

Thanks for this project. I've learned a lot about React Native.

I understand that you don't have an actual Android device. How much would it cost to get one in Brazil? I'd love to help out to show my appreciation.

Thanks!

**Comment by brunolemos** [comment]
Hi @kiliman!

There're devices from all price ranges, some $370 low end motorola, $800 Xiaomi Mi 8, $1100 Galaxy S9, all the way up to $1600 pixel 3 xl.

It's quite expensive here due to taxes.

Anyway, If you have some feedbacks and improvements suggestions about the Android version please open an issue and let me know!
