### ISSUE TITLE
402: Payment required

### ISSUE THREAD

**Issue by dance2die** [devhubapp/devhub#65]
devhubapp.com started displaying following error message.

![image](https://user-images.githubusercontent.com/8465237/50322725-5d6bbc00-04a4-11e9-9c62-e8216aedc1a9.png)

The link to `more` - https://zeit.co/docs/v2/routing/status-codes#402

_Anyone else getting this issue?_

**Comment by brunolemos** [comment]
@dance2die Yes I'm seeing this too, I've contacted [Zeit](https://zeit.co), seems to be a bug because the payment was made automatically lot's of hours ago.

**Comment by dance2die** [comment]
Thank you for the follow up~

Relieved as I thought it was my GitHub account failing 😀

**Comment by brunolemos** [comment]
Fixed. I had to make a new deploy, which shouldn't be necessary at all, since the payment was made automatically via credit card. cc @rauchg

**Comment by dguo** [comment]
@brunolemos, I see the same error message right now.

**Comment by paulogdm** [comment]
Is it possible that you have reached the daily limit @brunolemos ?

**Comment by brunolemos** [comment]
@paulogdm I don't think so, because it's just a single page static site with not that many daily access.

![image](https://user-images.githubusercontent.com/619186/50550216-0eb3e400-0c53-11e9-8b3e-817ef8c0ba6e.png)

**Comment by brunolemos** [comment]
Just to be clear last time I saw this payment error was 10 days ago, after that @dguo is the first to say for now

**Comment by dguo** [comment]
I tried again just now, and it is working for me. Maybe it was a caching issue?

**Comment by brunolemos** [comment]
@dguo ok! Maybe there's no problem then.

**Comment by paulogdm** [comment]
@dguo When you face the problem, please email support right away. We usually see that when someone downgraded the plan and expect the instances on a paid plan to keep running.
support@zeit.co

**Comment by brunolemos** [comment]
@paulogdm just fyi it happened again, but now with my `www` deployment. I re-deployed and it fixed. But not cool that this happens, makes no sense.

![image](https://user-images.githubusercontent.com/619186/55757130-a3379a80-5a29-11e9-9b1d-0df35740e607.png)

**Comment by paulogdm** [comment]
We will investigate... Thanks for letting me know.

**Comment by paulogdm** [comment]
@brunolemos You have downgraded to the Free plan at the end of Decemember. Since your deployment was created under the Unlimited plan, it was blocked because it *might* be crossing the limits (even if it’s not, we need to take precautions and block it). So in order to fix it, you can either upgrade to Unlimited, or re-deploy.
Please, delete deployments with a 402 (or upgrade your plan)

**Comment by brunolemos** [comment]
@paulogdm cool thanks, deleted old deploys
