### ISSUE TITLE
Couldn't find package " @devhub/components@0.39.2"

### ISSUE THREAD

**Issue by MrZhang123** [devhubapp/devhub#72]
### Environment

- yarn: 1.12.3
- node:10.13.0
- OS: MacOS 10.14.2

### Describe
I input command `yarn` for install package and get error log like this:

```sh
error Couldn't find package "@devhub/components@0.39.2" required by "@devhub/desktop@0.0.1" on the "npm" registry.
```

how to fix it ?

**Comment by brunolemos** [comment]
Fix was only on the `desktop` branch, it's on `master` now!
