### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by smaragdus** [devhubapp/devhub#77]
Please consider publishing DevHub on [F-Droid](https://f-droid.org/), there are people (like me) who do not use Google Play. I could not find the apk so I could not test it,

**Comment by brunolemos** [comment]
Thanks for your suggestion!

I took a look at F-Droid.

I don't currently plan doing this, at least not in the short term.
Everything new I decide to support is a maintenance cost that I add.
It can get hard for a single person.

There are websites that publish the `apk`, maybe you can download there?
E.g.: https://apkpure.com/devhub/com.devhubapp

> Note: I don't know if it's safe.

Another alternative is building the apk from source. 
Clone the repository, run `yarn`, `yarn studio` and generate the APK via `Build > Build APK`.

**Comment by smaragdus** [comment]
@brunolemos 

> Just curious, why exactly you don't use Google Play Store?

Privacy concerns, I use no Google services on my phone.

> There are websites that publish the `apk`, maybe you can download there?
> E.g.: https://apkpure.com/devhub/com.devhubapp

Thanks for the tip, a couple of days ago I checked [APKPure](http://website.com/) and I didn't find your app there. back then I found another [DevHub](https://apkpure.com/devhub/es.alejandrolora.devhub), not yours. Either I somehow missed it or your app was published after my search.

**Comment by linsui** [comment]
Could you publish the APK in GitHub release? Then we can download it directly and maybe DevHub can be published in IzzySoft's repo.

**Comment by IzzySoft** [comment]
Indeed I could pick the APK (if attached to a tag or located somewhere inside the repo) and put it into [my repo](https://apt.izzysoft.de/fdroid) (auto-updates within 24h of your publishing). And allowing your app into the official repo is a "one-time job", btw, as F-Droid does build the APK itself from the sources – so once listed, you'd just need to keep on tagging.

**Comment by brunolemos** [comment]
I'm open to publishing the apk somewhere if it's 100% automated, please make a pull request or detailed steps if possible

**Comment by IzzySoft** [comment]
It might qualify for the official repo as-is, if your library listing is complete (and the repo doesn't contain any binaries such as JARs): most of the libraries are using MIT license, one uses Apache-2, and your app GPL. I'm not sure if those licenses are compatible with each other, though – and I have no idea what Facebook Graph and Yarn use as license (FB Graph will certainly cause the `Tracking` AntiFeature, but that won't be a deal-breaker). Someone could give it a try and file an RFP with F-Droid to find out – but without knowing all licenses, that won't work out.

Could you attach the APKs to your [releases](https://github.com/devhubapp/devhub/releases), as you do with the desktop binaries (starting with the latest version is fully sufficient)? Then I could grab them and put them into my repository (my scanner then will also give us a list of the libraries it detects). Size fits, I would then keep the last 2 releases (updates will happen automatically within 24h of your attaching the APK to a new release).

**Comment by smaragdus** [comment]
@IzzySoft 

It is obvious that the developer is unwilling to release his software on free stores or at least provide APK downloads at [releases](https://github.com/devhubapp/devhub/releases) page. I can easily grab it using Aurora Store or other third party tools and services but it is not worth the effort. I will never revisit this project and I also deleted the [website](https://devhubapp.com/) from my bookmarks.

**Comment by IzzySoft** [comment]
@smaragdus I won't press for it. I'll take it when it's available (and get to know that), I also assist to bring it to the official repo when asked. But I've got enough other tasks on hand so I cannot effort running after it. As @brunolemos left this issue closed I tend to agree he won't support it. Though I don't understand what is so hard about attaching the APK to a release when making it. Not my decision. I myself no longer use Playstore at all, so manually grabbing the APK would mean missing on updates (where it in an F-Droid compatible repo, this would be different). Plus the app comes with Google trackers (Firebase, Analytics) which I prefer not to have.

@brunolemos should you change your mind, feel free to ping me.

**Comment by brunolemos** [comment]
>  I don't understand what is so hard about attaching the APK to a release when making it.

Just to give more context, I don't create github releases, I simply push a tag to the repository and electron-builder creates the release for me. I don't upload the desktop binaries, electron-builder builds and uploads them automatically for me. I don't deploy the web app, travis detected the github tag and does that for me.

So it's mostly automated. The only things left are ios and android. For this reason, sometimes the web version gets updated and the mobile end up staying outdated for some time, because it's take some annoying manual work. 

Also I don't generated apk, I generate the bundle format, but yes I can generate apk and upload it manually, I just wish this was automated. 

Devhub has 10k+ users and only 3 people suggested this so far. I'd love to get help automating it, specially from people that would benefit from having the apk there. That's what open source is for.

> I've got enough other tasks on hand so I cannot effort running after it

Exactly my case, I have to be laser focused on which tasks I do since I'm the only dev. And this one is not a one-time task, it's a manual one that should be remembered and done on every release. Unless someone automates it.

**Comment by brunolemos** [comment]
> the app comes with Google trackers (Firebase, Analytics) which I prefer not to have

Let me know some free alternatives, I'm willing to change it.

**Comment by IzzySoft** [comment]
@brunolemos thanks for clarification! And as said, I'm ready to assist when I can – e.g. when it shall be taken into the F-Droid repo, which is currently blocked by mentioned trackers. Not being an Android dev myself I cannot say what exactly you need; at F-Droid we usually recommend [ACRA](https://github.com/ACRA/acra) for crash reports/analytics. I've no idea about a Firebase replacement, sorry.

**Comment by brunolemos** [comment]
APK uploaded on latest release: https://github.com/devhubapp/devhub/releases/tag/v0.80.0

**Comment by IzzySoft** [comment]
Thanks @brunolemos! A little big for my repo (where the per-app limit is 20M), but I'd make an exception for that – weren't there those trackers. Especially, my library scanner reported:

* Bugsnag exception reporter for Android
* Google Mobile Services
* Firebase
* Google Analytics
* Google Tag Manager
* Firebase Analytics

Any chance to trim that down? Ideally to zero – but at least, why 4 analytics frameworks? Couldn't you drop 3 of them? For inclusion with the official F-Droid repo I'm afraid all of those need to go (not 100% sure of Bugsnag however).

**Comment by IzzySoft** [comment]
@brunolemos the APK is missing again with all releases after v0.95.0 – could you please attach it at least to the latest one again? Thanks!

**Comment by brunolemos** [comment]
@IzzySoft I haven't released any android version after that yet, it's 0.95.0 at the play store as well :)

**Comment by brunolemos** [comment]
@IzzySoft just curious, you don't seem to be using devhub, so how are you using the apk?

**Comment by IzzySoft** [comment]
Ah, my updater was just wondering about "newer tags without APKs".

As for your curiousity: there are Android users who cannot or do not want to use Play Store. For example, us "tin foils" prefer [F-Droid](https://f-droid.org/), which only serves FOSS apps. Naturally, that limits the selection, as F-Droid is pretty strict about building everything from source (so no blobs or proprietary libs allowed). This still leaves a "gray zone" of apps like yours: they are basically open source – but still use some libraries preventing it from an official F-Droid listing. As "nonfree" in Debian, for F-Droid there's my repo – and [your app in it](https://apt.izzysoft.de/fdroid/index/apk/com.devhubapp).

This should also explain my above concerns about that library list :wink:
