### ISSUE TITLE
homebrew cask formule

### ISSUE THREAD

**Issue by avelino** [devhubapp/devhub#78]
Create release for [homebrew cask](
https://github.com/Homebrew/homebrew-cask)

Related #2

**Comment by brunolemos** [comment]
Why?

**Comment by avelino** [comment]
All my software installs via brew, the desktop also (cask). I don't think that's just me.
This will give more viewability to the devhub

**Comment by brunolemos** [comment]
Thanks for the suggestion.

I don't currently plan doing this, at least not in the short term.
Everything new I decide to support is a maintenance cost that I add.
It can get hard for a single person.

I'll keep deploying only on GitHub releases and maybe Mac App Store soon.
