### ISSUE TITLE
Add homebrew Tap for automated installation on macOS

### ISSUE THREAD

**Issue by tusharjoshi** [devhubapp/devhub#91]
Maintain a github repository named homebrew-devhub just like available at https://github.com/tusharjoshi/homebrew-tusharjoshi
Create Casks/devhub.rb formula and maintain it with releases.

Users can add the Tap and install the Cask using following commands

```bash
brew tap devhubapp/devhub
brew cask install devhub
```

As this will be your repository you can maintain your cask file using your own automation tools.

**Comment by tusharjoshi** [comment]
Please create a repository https://github.com/devhubapp/homebrew-devhub so I can provide a PR for the new release in that repository for now.

homebrew-devhub - homebrew needs the name prepended as convention, while accessing the Tap it is accessed as devhubapp/devhub by dropping the homebrew word

**Comment by brunolemos** [comment]
For future reference: https://github.com/toolmantim/tap-release

**Comment by brunolemos** [comment]
@tusharjoshi I've created the https://github.com/devhubapp/homebrew-devhub repository, what's next?

**Comment by tusharjoshi** [comment]
Let me provide a PR for that repository to create the initial `Cask/devhub.rb` file

**Comment by tusharjoshi** [comment]
The Tap is created and commands mentioned in the README file.

**Comment by brunolemos** [comment]
@tusharjoshi I updated the repository with the v0.46.0 and the new sha, and ran both commands on my machine, but it still installs v0.45.4 instead. Any idea?

**Comment by brunolemos** [comment]
Maybe we need to remove from the homebrew repository? https://github.com/Homebrew/homebrew-cask/blob/b3b0092da658cf2484a25f649f5e2cffaa126fa4/Casks/devhub.rb

**Comment by tusharjoshi** [comment]
The default order of checking the cask is homebrew-cask first then homebrew-devhub that is why the old version is still used.  One solution for this is to use the install command like follows

```bash
brew cask reinstall devhubapp/devhub/devhub
```
This command will override the default order of casks.

And yes we should provide a PR to the main homebrew-cask repository to delete the devhub.rb file from the main repository.

**Comment by vitorgalvao** [comment]
> As this will be your repository you can maintain your cask file using your own automation tools.

I’ve seen another issue where you mention this. You do know you could also [automate submissions to the main Homebrew Cask repo](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask), don’t you? It’s literally one command:

```bash
cask-repair --cask-version VERSION_HERE --blind-submit devhub
```

That updates the cask *and* submits the PR, which is typically merged in a few minutes.
