### ISSUE TITLE
Add a feature for viewing previously visited repositories

### ISSUE THREAD

**Issue by singhrohan62** [devhubapp/devhub#92]
Hey @brunolemos , I think that for the user, previously viewed repositories feature should also be added. I think it would helpful for the user to directly view the previously visited repositories by him/her. Kindly share your views on this feature. Thank you!

**Comment by brunolemos** [comment]
Thanks for your suggestion!

I think it doesn't fit very much with DevHub goals, which is to keep up to date with what's going on.

Maybe you could just check your browser history?
Maybe you could star the repositories, or maybe you could use the Save for Later feature?

Thanks.
