### ISSUE TITLE
Duplicated image background

### ISSUE THREAD

**Issue by LeoColomb** [devhubapp/devhub#97]
Some images are duplicated and not well aligned.

![image](https://user-images.githubusercontent.com/846943/51446661-8be3ed80-1d15-11e9-8c90-1ca1f12e6806.png)

Original image:
![](https://avatars3.githubusercontent.com/u/4986074?s=50&v=4)

Thanks! 😽

**Comment by brunolemos** [comment]
Hi! Which browser? I did change this code to fix another issue but I don't see it duplicated on chrome.

**Comment by LeoColomb** [comment]
v0.44.0 on Chrome Version 71.0.3578.98 (64 bits) on Windows 10

**Comment by LeoColomb** [comment]
I'm a bit late, but yes, I still see this. Strange or not, this issue is not always visible.
