### ISSUE TITLE
Bookmark synchronization across environments

### ISSUE THREAD

**Issue by jusx** [devhubapp/devhub#98]
### Use Case
I currently use the DevHub Electron instance on my MacBook. I also have an instance on my iOS device. I bookmark items across the columns as a way to "pin" down things that needs further actions at a later time. It becomes one of my todo lists. 

### Problem
The bookmarks do not sync across environments. When I bookmark an item on the iOS device I don't see the same bookmarked item on my Electron instance.

### Question
Is this a bug or an enhancement that is not yet implemented?

**Comment by brunolemos** [comment]
Thanks for reporting! It's not implemented yet. I actually expected more people to complain about this but just a couple did.

I'll close since there is #70 to track this.

**Comment by jusx** [comment]
Thanks @brunolemos -- was searching the issues for "bookmark" before opening this issue. Will track #70
